### ISSUE TITLE
differentiate between brand, regular and solid symbols

### ISSUE THREAD

**Issue by zoharshavit** [smourier/FontAwesomeEnum#2]
Hi,
I'm using the free version of FA.
As you know, starting from version 5 icons have been wrapped in groups by style (regular, solid or brand) and their prefix is different (fab for brand far for regular etc..).
Can you think of a way for me to differentiate the symbols by automatically create an attribute like so:
`[Prefix("fab")]
/// <summary>
/// fa-accessible-icon glyph (f368).
/// </summary>
AccessibleIcon = 0xf368,`

so that later I will be able to get the prefix from that attribute with ease?
I did it by hand but every time FA comes out with a new version I'll need to do it again....
If only the less file contained the group for each of the symbols....
Am I making any sense?

Also, do you intent to publish a new less file every time FA release an update?

**Comment by smourier** [comment]
Hi,

I have added a feature that should do what you want. Just sync the project and recompile. Download FA 5 web somewhere on your disk, unzip it and now you can use a command line like this:

    FontAwesomeEnum.exe "C:\Users\kilroy\Downloads\fontawesome-free-5.1.0-web\less\_variables.less" FontAwesomeEnum.cs Prefix

So basically you point to the _variable.less that comes with FA 5, and add a "Prefix" last argument. This will tell the program to add attributes named "Prefix" to each definition (consts and enums). I have added a sample Prefix attribute, but you can use anything you want if it compiles in your environment.

    [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
    public class PrefixAttribute : Attribute
    {
        public PrefixAttribute(string name)
        {
            Name = name;
        }

        public string Name { get; }
    }

Result (note that some icons can have multiple prefixes):

    namespace FontAwesome
    {
	/// <summary>
	/// Font Awesome Resources V5.1.0
	/// </summary>
	public enum FontAwesomeEnum
	{
		/// <summary>
		/// fa-500px glyph (f26e).
		/// </summary>
		[Prefix("brands")]
		_500px = 0xf26e,

		/// <summary>
		/// fa-accessible-icon glyph (f368).
		/// </summary>
		[Prefix("brands")]
		AccessibleIcon = 0xf368,

		/// <summary>
		/// fa-accusoft glyph (f369).
		/// </summary>
		[Prefix("brands")]
		Accusoft = 0xf369,

		/// <summary>
		/// fa-address-book glyph (f2b9).
		/// </summary>
		[Prefix("regular")]
		[Prefix("solid")]
		AddressBook = 0xf2b9,

		/// <summary>
		/// fa-address-card glyph (f2bb).
		/// </summary>
		[Prefix("regular")]
		[Prefix("solid")]
		AddressCard = 0xf2bb,

**Comment by zoharshavit** [comment]
With some twicks that did the trick.
Thanks a lot.
