### ISSUE TITLE
Help for 5.10.0 Duotone

### ISSUE THREAD

**Issue by npagare** [smourier/FontAwesomeEnum#4]
Hi @smourier , how are you ?

Yesterday, FontAwesome team released first set of Duotones that has two layers of glyphs.
https://fontawesome.com/how-to-use/on-the-desktop/referencing-icons/duotone-icons

When I tried to use c# class based on your utility, I could access only the primary layer from the generated enums. 
FontAwesomeWebFont.PenAlt <= points to PenAlt-primary

Any thought on how do I access the secondary layer? in above example PenAlt-secondary
Will your utility need to process duotone.less  ?

Thanks

**Comment by smourier** [comment]
Hi,

These duotone things seems to be desktop only related. I don't see anything in the .less files. It would certainly require to add some code to FontAwesomeEnum yes.

**Comment by npagare** [comment]
Hi @smourier , 

Here is what I learned from FontAwesome support team.
It will work with web as there are two layers  and available in Solid only (for now).
...................................
Hi ,
So the secondary layers are in another private unicode space in the files.
If the unicode for a normal icon is \f200  then the secondary layer is \10f200 . Use basically shift the whole block by putting 10  in the front of the unicode hex value.
Hope that helps.
.....................................

Pulled your latest update. Didn't notice any new update when ran with -Prefix . Did  I miss anything ?

**Comment by npagare** [comment]
Hi @smourier ,

I am not sure if this link below - says duotone is supported on the web 
https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

**Comment by smourier** [comment]
Hi,

I've added experimental support for duo.
You can try it with a command line like this:

`FontAwesomeEnum.exe variables.less /duo`

or 

`FontAwesomeEnum.exe variables.less /duo FontAwesomeEnum.cs Prefix [path to svgs]`

I have only added a secondary enum for 'solid' icons. So, implicitely, the `duo` command requires a valid path to svgs.

Also, resources don't have a secondary because .NET `char` is only 16 bits, not 32.

Tell me if that's working for you.

**Comment by npagare** [comment]
@smourier , appreciate your response. trying .. 

In the meantime, will you please help me understand -
1>  why do we need _[path to svgs]_ on the the second command  unlike just -
_FontAwesomeEnum.exe variables.less /duo FontAwesomeEnum.cs Prefix_ ?
2> For using regular, light and brands fonts - will I have to run a separate non /duo command to create a separate .cs file ?
_FontAwesomeEnum.exe variables.less FontAwesomeEnum.cs Prefix_ 

[fyi - I am not by any mean expert on graphic design to understand font anatomy at detail level like you]

**Comment by smourier** [comment]
[path to svg] is by default "..\..\..\svgs". So it presumes in dev mode (I don't provide the binaries anyway...) you have the FontAwesome-provided "svgs" folder aside the FontAwesomeEnum.csproj file. If your svgs are elsewhere, then you can specify where they are

And we need the svgs to determine if an icon is in solid, brands or regular.

This is all very specific to FontAwesome.

**Comment by npagare** [comment]
**just got confirmation from FontAwesome support that duotone is supported for both desktop and web**

per my update note before - 
2> For using regular, light and brands fonts - will I have to run a separate non /duo command to create a separate .cs file ?
FontAwesomeEnum.exe variables.less FontAwesomeEnum.cs Prefix

BTW - above command is not writing Prefix in the .cs file as it used to before the last commit

3> running FontAwesomeEnum.exe variables.less /duo FontAwesomeEnum.cs Prefix  is failing because the default path is not looking at ..\svgs (which is peer to the less folder)  but at ..\..\svgs

Check the screenshot with and without svgs path .. I have smugged my directory path in the screenshot

![image](https://user-images.githubusercontent.com/26844611/62300729-f00e0980-b43c-11e9-8fe6-8e48b2cadeba.png)

**Comment by smourier** [comment]
Not sure what happens. Anyway I've made another version a bit more verbose. I can successfully generate everything with a command like this:

`FontAwesomeEnum.exe d:\Downloads\fontawesome-free-5.10.0-web\less\_variables.less FontAwesomeEnum.cs Prefix /duo
`

**Comment by npagare** [comment]
Hi @smourier , thank you!

- This time it did create enums but _it did not create resources for duo secondary layer_.
- It didn't add Prefix attributes for secondary layer

See pics below.

**_When you patch that, as highlighted in the pics below, may I please request you to help with-_**
1. **accepting a parameter that will take namespace of the class** / if not passed used your default one
(preferable that reflect the fontawesome version number e.g. FontAwesomeWeb5100Font)

2. **accepting a parameter for declaring name of the enum** / if not passed used your default one (preferable that reflect the fontawesome version number e.g. FontAwesomeWeb5100FontEnum)

3. **accepting a parameter for declaring name of the resource** / if not passed used your default one (preferable that reflect the fontawesome version number e.g. FontAwesomeWeb5100FontResources)

4. **declare resources as** public const **string**

5. **declare value of resources** inside _double quotes_ " "

6. **add a PrefixAttribute Class** below resource class
[AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
public class PrefixAttribute : Attribute
{
public PrefixAttribute(string name)
{
Name = name;
}
public string Name { get; }
}

7. **Add** following **using directives** on top of the class file
using System;
using System.Collections.Generic;
using System.Text;

I have been updating manually this every time fontawesome releases a new update; but will be a great help to me an to many of us out there. **_I really hope that you will consider my request._**

![image](https://user-images.githubusercontent.com/26844611/62329910-d8ef0c00-b47c-11e9-8e60-2fcddf900bdd.png)

![image](https://user-images.githubusercontent.com/26844611/62329462-8f51f180-b47b-11e9-81e9-40dac6b7904a.png)

**Comment by smourier** [comment]
As I said earlier, resources are not created because duotone are 24 bits codepoints (which means they're store on 32bits) while .NET char is 16bits. Even with strings, you can't declare the duotones as characters. 

Duotone is not a prefix, just another "thing", that's why I don't add any prefix attribute for them, and why I don't add a a "duotone" prefix.

What you can do is fork  the whole project and modify the code so it does exactly what you do, it shouldn't be very complicated. After all, this is what open source brings.

**Comment by npagare** [comment]
Hi @smourier - I will do that.
When tested and ready, I will send you a PR if you are open for that.

**Comment by smourier** [comment]
Not really, it's specific to your needs, from my point of view.
